version: "3.8"
services:
  limesurvey-ce:
    image: bestrada23685/limesurvey-ce:${VERSION}-${BUILD}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
        BUILD: ${BUILD}
    container_name: limesurvey-ce-v6-github
    secrets:
      - limedb6_pass
      - limeadmin6_pass
    env_file:
      - ./config/.env
    ports:
      - "80:80"
    depends_on:
      - postgres-db
    volumes:
      - dev6-upload:/var/www/html/limesurvey/upload
      - dev6-plugins:/var/www/html/limesurvey/plugins
  postgres-db:
    image: postgres:15.3-bullseye
    container_name: postgres-db
    secrets:
      - limedb6_pass
    env_file:
      - ./config/.env
    volumes:
      - dbdev6-data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    secrets:
      - pgadmin6_pass
    ports:
      - "81:80"
    depends_on:
      - postgres-db
    env_file:
      - ./config/.env
    volumes:
      - ./config/pgadmin4/servers.json:/pgadmin4/servers.json
      - ./config/pgadmin4/pgpass:/pgadmin4/pgpass
secrets:
  limedb6_pass:
    file: ./secrets/limedb6_pass.txt
  limeadmin6_pass:
    file: ./secrets/limeadmin6_pass.txt
  pgadmin6_pass:
    file: ./secrets/pgadmin6_pass.txt
volumes:
  dbdev6-data:
  dev6-upload:
  dev6-plugins:
