version: "3.8"
services:
  limesurvey-ce:
    image: bestrada23685/limesurvey-ce:${VERSION}-${BUILD}
    build:
      args:
        VERSION: ${VERSION}
        BUILD: ${BUILD}
    container_name: limesurvey-ce-prov5
    secrets:
      - limedb_pass
      - limeadmin_pass
    env_file:
      - ./config/.env
    ports:
      - "80:80"
    depends_on:
      - postgres-db
    volumes:
      - pro5-upload:/var/www/html/default.uni.edu.ni/upload
      - pro5-plugins:/var/www/html/default.uni.edu.ni/plugins
  postgres-db:
    image: postgres:12.12-bullseye
    container_name: postgres-db
    secrets:
      - limedb_pass
    env_file:
      - ./config/.env
    ports:
      - "5432:5432"
    volumes:
      - dbpro5-data:/var/lib/postgresql/data
secrets:
  limedb_pass:
    file: ./secrets/limedb_pass.txt
  limeadmin_pass:
    file: ./secrets/limeadmin_pass.txt
volumes:
  dbpro5-data:
  pro5-upload:
  pro5-plugins:
