version: "3.8"
services:
  limesurvey-ce:
    image: bestrada23685/limesurvey-ce:${VERSION}-${BUILD}
    build:
      context: ./limesurvey-ce
      dockerfile: Dockerfile.GitHub
      args:
        VERSION: ${VERSION}
        BUILD: ${BUILD}
    container_name: limesurvey-ce-github
    secrets:
      - limedb_pass
      - limeadmin_pass
    environment:
      DB_HOST: postgres-db
      DB_NAME: limedbdev
      DB_USERNAME: limeusrdev
      DB_PASSWORD_FILE: /run/secrets/limedb_pass
      ADMIN_USERNAME: bestrada623dev
      ADMIN_PASSWORD_FILE: /run/secrets/limeadmin_pass
      ADMIN_FULLNAME: Bakneer Estrada
      ADMIN_EMAIL: bakneer.estrada623@std.uni.edu.ni
    ports:
      - "80:80"
    depends_on:
      - postgres-db
    volumes:
      - upload:/var/www/html/limesurvey/upload
      - plugins:/var/www/html/limesurvey/plugins
  postgres-db:
    container_name: postgres
    image: postgres:12.12-bullseye
    secrets:
      - limedb_pass
    environment:
      POSTGRES_USER: limeusrdev
      POSTGRES_PASSWORD_FILE: /run/secrets/limedb_pass
      POSTGRES_DB: limedbdev
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    secrets:
      - pgadmin_pass
    ports:
      - "8081:80"
    depends_on:
      - postgres-db
    environment:
      PGADMIN_DEFAULT_EMAIL: bakneer.estrada623@std.uni.edu.ni
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_pass
volumes:
  db-data:
  upload:
  plugins:
secrets:
  limedb_pass:
    file: ./secrets/github/limedb_pass.txt
  limeadmin_pass:
    file: ./secrets/github/limeadmin_pass.txt
  pgadmin_pass:
    file: ./secrets/github/pgadmin_pass.txt