version: "3.8"
services:
  limesurvey-ce:
    container_name: limesurvey-ce
    image: bestrada23685/limesurvey-ce:5.3.32-220817
    secrets:
      - limedb_pass
      - limeadmin_pass
    environment:
      DB_HOST: postgres-db
      DB_NAME: limedbpro5
      DB_USERNAME: limeusrpro5
      DB_PASSWORD_FILE: /run/secrets/limedb_pass
      ADMIN_USERNAME: bestrada623pro
      ADMIN_PASSWORD_FILE: /run/secrets/limeadmin_pass
      ADMIN_FULLNAME: Bakneer Estrada
      ADMIN_EMAIL: bakneer.estrada623@std.uni.edu.ni
    ports:
      - "80:80"
    depends_on:
      - postgres-db
    volumes:
      - upload:/var/www/html/limesurvey/upload
      - plugins:/var/www/html/limesurvey/plugins
  postgres-db:
    container_name: postgres
    image: postgres:12.12-bullseye
    secrets:
      - limedb_pass
    environment:
      POSTGRES_USER: limeusrpro5
      POSTGRES_PASSWORD_FILE: /run/secrets/limedb_pass
      POSTGRES_DB: limedbpro5
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    secrets:
      - pgadmin_pass
    ports:
      - "8081:80"
    depends_on:
      - postgres-db
    environment:
      PGADMIN_DEFAULT_EMAIL: bakneer.estrada623@std.uni.edu.ni
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_pass
volumes:
  db-data:
  upload:
  plugins:
secrets:
  limedb_pass:
    file: ./secrets/v5/pro/limedb_pass.txt
  limeadmin_pass:
    file: ./secrets/v5/pro/limeadmin_pass.txt
  pgadmin_pass:
    file: ./secrets/v5/pro/pgadmin_pass.txt