version: "3.8"
services:
  limesurvey-ce:
    image: bestrada23685/limesurvey-ce:${VERSION}-${BUILD}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: ${VERSION}
        BUILD: ${BUILD}
    container_name: limesurvey-ce-v6
    secrets:
      - limedb_pass
      - limeadmin_pass
    env_file:
      - ./config/.env
    ports:
      - "80:80"
    depends_on:
      - postgres-db
    volumes:
      - limev6-upload:/var/www/html/default.uni.edu.ni/upload
      - limev6-plugins:/var/www/html/default.uni.edu.ni/plugins
  postgres-db:
    image: postgres:15.3-bullseye
    container_name: postgres-db
    secrets:
      - limedb_pass
    env_file:
      - ./config/.env
    volumes:
      - dbv6-data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    secrets:
      - pgadmin_pass
    ports:
      - "81:80"
    depends_on:
      - postgres-db
    env_file:
      - ./config/.env
    volumes:
      - ./config/pgadmin4/servers.json:/pgadmin4/servers.json
      - ./config/pgadmin4/pgpass:/pgadmin4/pgpass
secrets:
  limedb_pass:
    file: ./secrets/limedb_pass.txt
  limeadmin_pass:
    file: ./secrets/limeadmin_pass.txt
  pgadmin_pass:
    file: ./secrets/pgadmin_pass.txt
volumes:
  dbv6-data:
  limev6-upload:
  limev6-plugins:
