version: "3.8"
services:
  limesurvey-ce:
    image: bestrada23685/limesurvey-ce:6.1.4-230620
    secrets:
      - limedb6_pass
      - limeadmin6_pass
    env_file:
      - ./config/.env
    ports:
      - "80:80"
    depends_on:
      - postgres-db
    volumes:
      - upload6:/var/www/html/default.uni.edu.ni/upload
      - plugins6:/var/www/html/default.uni.edu.ni/plugins
  postgres-db:
    image: postgres:15.3-bullseye
    secrets:
      - limedb6_pass
    env_file:
      - ./config/.env
    ports:
      - "5432:5432"
    volumes:
      - data6:/var/lib/postgresql/data
secrets:
  limedb6_pass:
    external: true
  limeadmin6_pass:
    external: true
volumes:
  data6:
  upload6:
  plugins6:
